version: '3.8'

services:
  app:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 enter:app
    volumes:
      - ./application/templates/main:/futbolero/application/templates/main
      - ./application/templates/auth:/futbolero/application/templates/auth
      - ./application/templates/posts:/futbolero/application/templates/posts
      - ./application/static:/futbolero/application/static
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - db
      - redis
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASS}
      POSTGRES_DB: ${PSQL_DB_NAME}
  redis:
    image: redis:latest

volumes:
  postgres_data: